### ISSUE TITLE
Thermostat FAN and ECO mode

### ISSUE THREAD

**Issue by rpersche** [potmat/homebridge-google-nest-sdm#23]
Hi,

Thanks for your great work!

If I read this correctly, the API allows now for setting the FAN and ECO mode. https://developers.google.com/nest/device-access/api/thermostat. 

Would it be possible to enable that?

**Comment by potmat** [comment]
ECO mode is already there.  Unfortunately there's no way to see it in the Apple Home app.  If you use an alternative HomeKit app like Home+ or Eve you will see the Eco button.  This is because Homebridge does not offer a way to extend the default controls the Home app provides.  That is, the Apple Home app does not have an "eco" button for thermostats, so the only way to add one would be to add something like a dummy light switch.  This was not a path I wanted to take.


As for FAN mode you're right, that must be new!  I'll take a look at it.

**Comment by potmat** [comment]
Hi @rpersche,

Sorry for the delay.  I was looking into the fan thing today and I'm not sure it makes sense to add.  The way the fan seems to work in the SDM API is that you can turn it on for a specified time (defaults to 15 minutes) after which it turns off.  Why you would want to do this I have no idea... However, HomeKit/Homebridge do not have any concept of a "fan timer", in fact HomeBridge thermostats do not even have any properties related to fans! I suppose it's assumed that your furnace will run the fan as necessary and there's no reason you'd need to manually control it.  I could add a fan control that you could turn on/off, however when you turned it on there would be no way to specify the time, it would have to default to 15 minutes or some other time.

Personally this feels like not a good fit and not very usable/intuitive.  Let me know your thoughts.

**Comment by rpersche** [comment]
Hi @potmat, 

Thanks for taking the time to look into this. The fan timer is useful for moving the air around in your house/room in case you don't have a cross breeze. I used to have a scene called "Air out my place" which opened my window and triggered the Nest fan. Then, when the Nest switched to heating, it triggered another scene to close my window again :)

homebridge-nest has a setting for the duration
"fanDurationMinutes": number of minutes to run the fan when manually turned on (optional, default is 15)

**Comment by trevoralan** [comment]
Just my two cents, my wife and I use the fan function every day to move air rather than change the temp. This is by far the best Nest integration thus far, just wish there was a fan function to even just set a default fan time to turn on.

**Comment by trevoralan** [comment]
I'd go a step further and say that since HomeKit allows for basic automation to control the timing, you could setup a fan switch with this API call for ON:

POST /enterprises/project-id/devices/device-id:executeCommand
{
  "command" : "sdm.devices.commands.Fan.SetTimer",
  "params" : {
    "timerMode" : "ON",
    "duration" : "43200s"
  }
}

And this for OFF:

POST /enterprises/project-id/devices/device-id:executeCommand
{
  "command" : "sdm.devices.commands.Fan.SetTimer",
  "params" : {
    "timerMode" : "OFF"
  }
}

This would obviously turn the fan on for 12 hours, but at least it would provide for easy access and control. I am a serious novice hear but would gladly help (I am currently digging through your beautiful code to try and decipher)

**Comment by potmat** [comment]
Hi @trevoralan, yes you are correct those are the endpoints the API would call.  This would actually be quite simple for me to add.

The reason I've hesitated is that I don't like adding fake switches that actually control things that aren't switches etc. A lot of other Homebridge plugins do this and it just feels hacky to me.

The other thing holding me back is that the API doesn't have any way to determine if your thermostat is even connected to a fan.  For example my house uses radiators, there's no fan.  But since the API doesn't give any information about what the thermostat is actually connected to I would get a fan switch as well, even though it does nothing.

I'm open to suggestions.

**Comment by trevoralan** [comment]
@potmat , thanks for getting back so quickly! I completely understand the "hackiness" of the fan being a switch but in all honesty, as the fan doesn't have any speeds, it really is just in an on and off state. I have used the fan on other much-less-than modules and they try to complicate it by adding in a field where you can choose your default fan on duration. I think it really can just be as simple as turning the fan on or off as it should be. The fan doesn't consume a lot of electricity at all, hence my suggestion to default to the longest duration possible, 12 hours (43200s). I know I am being selfish here as you would be the one to ultimately implement, but I truly thing many would benefit and it would put the nice bow on an already stellar module.

**Comment by DTxAg** [comment]
@potmat, I too could really use the fan switches. I might suggest doing what some other plugins do and giving the user the option of adding a fan switch if they want it. For example, I use the Screenlogic plugin for pool control, and the settings there let you decide whether to create separate switches for the individual light colors. You could just add something in the settings of your plugin that would allow the user to decide whether to create a fan switch. If they turn it on, then give them the option of picking the amount of time to run the fan.

We use the fan switches because a couple rooms in our house get hotter than other rooms. Turning on the fans help to move air between the cooler rooms (where the thermostats are located) to the warmer rooms.

**Comment by potmat** [comment]
Ok why not, I'll look into it as soon as I can.

**Comment by potmat** [comment]
Just pushed version 1.1.12, which add support for the thermostat fan.  I don't have a fan myself, so hopefully it works correctly.

**Comment by potmat** [comment]
@rpersche:  You're perfectly welcome! Sorry it took almost a year.

Can you verify also that when the time runs out and the fan turns off it shows as off in the Home app?

**Comment by rpersche** [comment]
Yes, it works that way. Very nice. 
Also, turning off the fan while the timer is still running, works!

**Comment by guillochon** [comment]
Just installed this plugin as the old google nest plugin no longer works...everything is great *except* there's no ECO mode like there was in the old plugin. In the other plugin it was indeed just implemented as a simple switch. Would it be possible to add such a switch here @potmat? I was using the switch to do things like turn on eco mode when everyone had left the house, turn it on when the first person arrived, etc.

**Comment by potmat** [comment]
@guillochon, you can still do this, you just need to setup your automation in something like Eve or Home+ as the native Apple Home app will not support it.

**Comment by guillochon** [comment]
@potmat I don't think I can, at least in Eve, because you cannot create automations that control the home in Eve (only set up triggers/conditions). All the "control" aspects must be set up in the Home app itself, which is impossible since the Eco switch is not exposed there.

**Comment by potmat** [comment]
@guillochon : What about Home+?

**Comment by rpersche** [comment]
@guillochon I created scenes "Turn on ECO mode" "Turn off ECO mode" in Eve, and then I can use the scenes in Home

**Comment by guillochon** [comment]
@rpersche Oh ok that's a neat workaround, I'll give that a try

@potmat Home+ is $15, I don't own it so I don't know
