### ISSUE TITLE
Filter motion type on camera/doorbell camera events

### ISSUE THREAD

**Issue by beaverly72** [potmat/homebridge-google-nest-sdm#51]
This is obviously not a bug, but an enhancement request.  I have no idea what data is provided by the camera/doorbell events, but if it does have motion types, e.g. motion, person, package, etc. I was wondering if it would be possible to filter by motion type at some point.  I'd like to only send motion events to Homekit that my nest doorbell comera identifies as a person.  I am using this to create a Homekit automation to turn on my outside lights.  It seems I cannot select specific motion types in the automation.

**Comment by potmat** [comment]
The SDM API supports three types of camera events: Motion, person, and sound.  The first two are reported to Homebridge as motion.  The third is not reported.

As far as I can tell there is no way to tell Homebridge that the motion is caused by a person, just that there was motion https://developers.homebridge.io/#/service/MotionSensor. If you know of a way please let me know.

**Comment by beaverly72** [comment]
> The SDM API supports three types of camera events: Motion, person, and sound.  The first two are reported to Homebridge as motion.  The third is not reported.
> 
> 
> 
> As far as I can tell there is no way to tell Homebridge that the motion is caused by a person, just that there was motion https://developers.homebridge.io/#/service/MotionSensor. If you know of a way please let me know.

I figured Nest was just sending a motion event and HomeKit determined the type. Worth a shot.  Thanks for the response. This can be closed as far as I'm concerned.
