### ISSUE TITLE
Doorbell chime twice per press

### ISSUE THREAD

**Issue by Stormeh** [potmat/homebridge-google-nest-sdm#85]
Hi - I've got the 2021 Nest Doorbell (battery) - I've got it setup successfully on homebridge and is working for all intents and purposes.

However I've noticed when I press the doorbell, there will be 2 chimes - It appears on both STARTED and ENDED a notification will be sent to my device and my homepods will also chime. 

[6/5/2023, 3:07:39 PM] [homebridge-google-nest-sdm] Event received: {
"eventThreadState": "STARTED"
[6/5/2023, 3:07:39 PM] [homebridge-google-nest-sdm] Doorbell ring! Entrance Doorbell

[6/5/2023, 3:07:58 PM] [homebridge-google-nest-sdm] Event received: {
  "eventThreadState": "ENDED"
[6/5/2023, 3:07:58 PM] [homebridge-google-nest-sdm] Doorbell ring! Entrance Doorbell

**Comment by potmat** [comment]
Just pushed v1.1.4 which should fix the issue.  

I spent some time trying to play around with caching events so that I could use the motion start/stop events, but in the end I ignored them and used the same motion decay time I've always used, the extra complexity of accurately reporting when motion has "started" and "stopped" wasn't worth it.

**Comment by Stormeh** [comment]
Thank you so much - Tested and it's working perfectly.
